[package]
name = "actions-toolkit"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0.96" }
serde = { version = "1.0.163", features = ["derive"] }
thiserror = { version = "1.0.40" }
uuid = { version = "1.3.3", features = ["v4"] }
log = { version = "0.4.19" }
