on:
  push:
   branches: [ 'main' ]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Build
      run: |
        sudo apt install musl-tools && \
        rustup target add x86_64-unknown-linux-musl && \
        cargo build --release --target=x86_64-unknown-linux-musl