on:
  push:
   branches: [ 'main' ]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Build
      run: |
        rustup target add x86_64-unknown-linux-musl && \
        cargo build --release --target=x86_64-unknown-linux-musl